# Generated by Django 3.2 on 2022-11-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('percent_off', models.DecimalField(decimal_places=2, max_digits=4)),
                ('duration', models.CharField(choices=[('once', 'once'), ('repeating', 'repeating'), ('forever', 'forever')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('сurrency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('inclusive', models.BooleanField(default=False)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.CharField(max_length=100)),
                ('tax_rate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounts', models.ManyToManyField(to='items.Discount')),
                ('items', models.ManyToManyField(to='items.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.tax'),
        ),
    ]
